/**
 * Curated registry of recompression / hyperbaric chambers for dive-mode PACE planning.
 *
 * Two entry classes:
 *
 *  manual: true  — Hand-curated entries from DAN, Royal/US Navy, and national dive-medicine
 *                  directories. These cover Europe and key military chambers not on the UHMS
 *                  accredited list. The auto-refresh script NEVER touches these entries.
 *
 *  (no manual)   — UHMS-accredited facilities (auto-generated by
 *                  scripts/refreshHyperbaricChambers.mjs). Re-run to pick up new accreditations
 *                  or corrected coordinates. These appear below the delimiter comment.
 *
 * Merge behaviour (in merge.ts):
 *  - If a registry entry is within 200 m of an already-merged hospital (by name similarity),
 *    the hospital's capabilities array is enriched with 'hyperbaric' rather than adding a
 *    duplicate record.
 *  - Otherwise, a standalone FacilityRecord with isChamber:true is injected.
 *
 * Manual data compiled from:
 *   - DAN (Divers Alert Network) emergency chamber directory
 *   - UHMS (Undersea and Hyperbaric Medical Society) facility locator
 *   - Royal Navy / US Navy diving medicine directories
 *   - Official facility websites
 *
 * UHMS auto-section: https://www.uhms.org/accredited-facilities.html
 *
 * Last reviewed: 2026-07
 *
 * To add a manual entry: fill all required fields, set manual:true, and note the source.
 * The `availability` field is surfaced on the PACE screen / slide notes.
 * To refresh UHMS entries: npm run refresh:chambers (from app/ directory).
 */

import type { LatLon } from '../../calc/geo'

export interface HyperbaricChamber {
  /** Human-readable canonical name shown in the PACE plan. */
  name: string
  /** WGS-84 latitude (decimal degrees). */
  lat: number
  /** WGS-84 longitude (decimal degrees). */
  lon: number
  /** Primary contact / emergency line. */
  phone?: string
  /** Street / city address. */
  address?: string
  /** Availability note, e.g. "24/7 emergency" or "On-call — call before arrival". */
  availability?: string
  /** Shown in the PACE screen notes field. */
  notes?: string
  /** Country the facility is in (used by the validator). */
  country?: string
  /** UHMS "Accredited With Distinction" marker (*). Auto-set by the refresh script. */
  distinction?: boolean
  /**
   * Hand-curated entry — the auto-refresh script never modifies or removes these.
   * Set to true for non-UHMS chambers (DAN, Royal Navy, national directories) and
   * for any UHMS chamber that needs manually-verified coords or custom notes.
   */
  manual?: boolean
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const HYPERBARIC_CHAMBERS: readonly HyperbaricChamber[] = [

  // ────────────────────────────────────────────────────────────────────────────
  // MANUAL ENTRIES — hand-curated; do not delete or auto-overwrite
  // Sources: DAN, Royal/US Navy, national dive-medicine directories
  // ────────────────────────────────────────────────────────────────────────────

  // ── United States ──────────────────────────────────────────────────────────

  // Source: DAN 24-hr emergency line directs to Duke; UHMS directory
  {
    name: 'Duke Hyperbaric Center',
    lat: 35.9056, lon: -78.9443,
    phone: '+1 919-684-8111',
    address: '40 Duke Medicine Circle, Durham, NC 27710',
    availability: '24/7 emergency',
    notes: 'Primary DAN US referral centre. Dive medicine specialists on call.',
    country: 'United States',
    manual: true,
  },

  // Source: UHMS directory; Massachusetts General Hospital
  {
    name: 'Massachusetts General Hospital — Hyperbaric Medicine',
    lat: 42.3628, lon: -71.0681,
    phone: '+1 617-726-2000',
    address: '55 Fruit Street, Boston, MA 02114',
    availability: '24/7 emergency',
    notes: 'Harvard-affiliated Level I trauma + hyperbaric unit.',
    country: 'United States',
    manual: true,
  },

  // Source: US Navy, Naval Medical Center Portsmouth
  {
    name: 'Naval Medical Center Portsmouth — Hyperbaric Treatment Center',
    lat: 36.8484, lon: -76.2979,
    phone: '+1 757-953-5966',
    address: '620 John Paul Jones Circle, Portsmouth, VA 23708',
    availability: '24/7 emergency (military/DoD priority)',
    notes: 'US Navy hyperbaric facility; accepts civilian dive casualties.',
    country: 'United States',
    manual: true,
  },

  // Source: US Navy, Naval Medical Center San Diego
  {
    name: 'Naval Medical Center San Diego — Hyperbaric Medicine',
    lat: 32.7236, lon: -117.1571,
    phone: '+1 619-532-7206',
    address: '34800 Bob Wilson Drive, San Diego, CA 92134',
    availability: '24/7 emergency (military/DoD priority)',
    notes: 'West Coast US Navy hyperbaric facility.',
    country: 'United States',
    manual: true,
  },

  // Source: UTMB Galveston; UHMS directory
  {
    name: 'UTMB Health — Hyperbaric Medicine Program',
    lat: 29.3105, lon: -94.7749,
    phone: '+1 409-772-1855',
    address: '301 University Blvd, Galveston, TX 77555',
    availability: '24/7 emergency',
    notes: 'Gulf Coast DAN referral. Dive medicine research facility.',
    country: 'United States',
    manual: true,
  },

  // Source: Jackson Memorial / UM Miller School of Medicine
  {
    name: 'Jackson Memorial Hospital — Hyperbaric Center',
    lat: 25.7951, lon: -80.2078,
    phone: '+1 305-585-1111',
    address: '1611 NW 12th Avenue, Miami, FL 33136',
    availability: '24/7 emergency',
    notes: 'Primary hyperbaric referral for the Florida Keys and Caribbean dive casualties.',
    country: 'United States',
    manual: true,
  },

  // Source: UHMS; Cleveland Clinic
  {
    name: 'Cleveland Clinic — Hyperbaric Medicine Center',
    lat: 41.5024, lon: -81.6219,
    phone: '+1 216-444-8000',
    address: '9500 Euclid Avenue, Cleveland, OH 44195',
    availability: '24/7 emergency',
    country: 'United States',
    manual: true,
  },

  // Source: UHMS; Albany Medical Center
  {
    name: 'Albany Medical Center — Hyperbaric Medicine',
    lat: 42.6543, lon: -73.7618,
    phone: '+1 518-262-3125',
    address: '43 New Scotland Avenue, Albany, NY 12208',
    availability: '24/7 emergency',
    notes: 'DAN referral for Northeast US.',
    country: 'United States',
    manual: true,
  },

  // Source: UCSF / Stanford — VA Palo Alto is major West Coast chamber
  {
    name: 'VA Palo Alto Health Care System — Hyperbaric Medicine',
    lat: 37.3951, lon: -122.1341,
    phone: '+1 650-493-5000',
    address: '3801 Miranda Avenue, Palo Alto, CA 94304',
    availability: '24/7 emergency (priority to veterans; accepts civilians)',
    country: 'United States',
    manual: true,
  },

  // Source: UAB Medicine; DAN Southeast
  {
    name: 'UAB Medicine — Hyperbaric Oxygen Therapy Program',
    lat: 33.5022, lon: -86.7994,
    phone: '+1 205-934-4011',
    address: '1808 7th Avenue South, Birmingham, AL 35233',
    availability: '24/7 emergency',
    country: 'United States',
    manual: true,
  },

  // Source: Dartmouth Health; DAN Northeast
  {
    name: 'Dartmouth Hitchcock Medical Center — Hyperbaric Medicine',
    lat: 43.6461, lon: -72.2999,
    phone: '+1 603-650-5000',
    address: '1 Medical Center Drive, Lebanon, NH 03756',
    availability: '24/7 emergency',
    country: 'United States',
    manual: true,
  },

  // Source: Mayo Clinic Rochester; UHMS
  {
    name: 'Mayo Clinic — Hyperbaric Medicine',
    lat: 44.0225, lon: -92.4661,
    phone: '+1 507-284-2511',
    address: '200 First Street SW, Rochester, MN 55905',
    availability: '24/7 emergency',
    country: 'United States',
    manual: true,
  },

  // Source: Harborview / UW Medicine; DAN Northwest
  {
    name: 'Harborview Medical Center — Hyperbaric Medicine',
    lat: 47.6036, lon: -122.3282,
    phone: '+1 206-744-3000',
    address: '325 9th Avenue, Seattle, WA 98104',
    availability: '24/7 emergency',
    notes: 'UW Medicine Level I trauma. DAN Pacific Northwest referral.',
    country: 'United States',
    manual: true,
  },

  // ── United Kingdom ─────────────────────────────────────────────────────────

  // Source: DDRC Healthcare website; DAN Europe; BSAC
  {
    name: 'DDRC Healthcare — Hyperbaric Unit',
    lat: 50.3870, lon: -4.1240,
    phone: '+44 1752 209999',
    address: 'Tamar Science Park, Research Way, Plymouth PL6 8BU',
    availability: '24/7 emergency',
    notes: 'Diving Diseases Research Centre. Primary UK DAN referral. On-call 24/7.',
    country: 'United Kingdom',
    manual: true,
  },

  // Source: London Hyperbaric Medicine; Whipps Cross University Hospital
  {
    name: 'London Hyperbaric Medicine — Whipps Cross Hospital',
    lat: 51.5869, lon: -0.0068,
    phone: '+44 20 8535 6443',
    address: 'Whipps Cross University Hospital, Leytonstone, London E11 1NR',
    availability: '24/7 emergency',
    notes: 'Primary hyperbaric referral for London and South East England.',
    country: 'United Kingdom',
    manual: true,
  },

  // Source: BSAC; RN diving medicine; NHS Scotland
  {
    name: 'Wirral Hyperbaric Unit — Clatterbridge Hospital',
    lat: 53.3556, lon: -3.0509,
    phone: '+44 151 334 4000',
    address: 'Clatterbridge Hospital, Bebington, Wirral CH63 4JY',
    availability: 'On-call — call before arrival',
    notes: 'Covers North West England and North Wales dives.',
    country: 'United Kingdom',
    manual: true,
  },

  // Source: Royal Navy; INM Alverstoke
  {
    name: 'Institute of Naval Medicine — Hyperbaric Facility',
    lat: 50.8012, lon: -1.1364,
    phone: '+44 2392 768026',
    address: 'Crescent Road, Alverstoke, Gosport PO12 2DL',
    availability: '24/7 emergency (Royal Navy; accepts civilian dive casualties)',
    notes: 'Royal Navy primary hyperbaric facility. Formerly Fort Blockhouse.',
    country: 'United Kingdom',
    manual: true,
  },

  // ── France ────────────────────────────────────────────────────────────────

  // Source: CHU Brest; DAN Europe; FFESSM
  {
    name: 'CHU de Brest — Centre Hyperbare (Cavale Blanche)',
    lat: 48.3749, lon: -4.4736,
    phone: '+33 2 98 34 73 07',
    address: 'Boulevard Tanguy Prigent, 29200 Brest',
    availability: '24/7 emergency',
    notes: 'Covers Atlantic coast, Channel diving casualties. Naval proximity.',
    country: 'France',
    manual: true,
  },

  // Source: AP-HM; DAN Europe; FFESSM
  {
    name: 'Hôpital Sainte-Marguerite (AP-HM) — Médecine Hyperbare',
    lat: 43.2631, lon: 5.3967,
    phone: '+33 4 91 74 40 74',
    address: '270 Boulevard de Sainte-Marguerite, 13009 Marseille',
    availability: '24/7 emergency',
    notes: 'Covers French Riviera, Corsica, and Western Mediterranean dive casualties.',
    country: 'France',
    manual: true,
  },

  // ── Netherlands ───────────────────────────────────────────────────────────

  // Source: Erasmus MC; DAN Europe; KNMG
  {
    name: 'Erasmus MC — Hyperbarische Geneeskunde',
    lat: 51.9117, lon: 4.4697,
    phone: '+31 10 703 4222',
    address: "Doctor Molewaterplein 40, 3015 GD Rotterdam",
    availability: '24/7 emergency',
    notes: 'Primary hyperbaric referral for Netherlands and North Sea dive casualties.',
    country: 'Netherlands',
    manual: true,
  },

  // ── Germany ───────────────────────────────────────────────────────────────

  // Source: Bundeswehr diving medicine; DAN Europe
  {
    name: 'Marineschule Mürwik — Tauchtauglichkeitszentrum (Druckkammer)',
    lat: 54.8252, lon: 9.4622,
    phone: '+49 461 864 7415',
    address: 'Admiralitätstraße 1, 24944 Flensburg',
    availability: '24/7 emergency (Bundeswehr; accepts civilian casualties)',
    notes: 'German Navy hyperbaric facility. North Sea / Baltic dive medicine.',
    country: 'Germany',
    manual: true,
  },

  // Source: Druckkammer Köln; GTÜM
  {
    name: 'Uniklinik Köln — Abteilung für Tauchmedizin und Hyperbarie',
    lat: 50.9278, lon: 6.9177,
    phone: '+49 221 478 32671',
    address: 'Kerpener Str. 62, 50937 Köln',
    availability: '24/7 emergency',
    notes: 'Major inland German hyperbaric centre; covers Rhine corridor.',
    country: 'Germany',
    manual: true,
  },

  // ── Spain ─────────────────────────────────────────────────────────────────

  // Source: Hospital del Mar; DAN Europe; FEDAS
  {
    name: 'Hospital del Mar — Unidad de Medicina Hiperbárica',
    lat: 41.3960, lon: 2.1941,
    phone: '+34 93 248 3000',
    address: 'Passeig Marítim de la Barceloneta 25-29, 08003 Barcelona',
    availability: '24/7 emergency',
    notes: 'Primary hyperbaric referral for Catalonia and Western Mediterranean.',
    country: 'Spain',
    manual: true,
  },

  // ── Norway ────────────────────────────────────────────────────────────────

  // Source: Oslo University Hospital; DAN Europe; Norsk Dykkemedisiner Forening
  {
    name: 'Oslo Universitetssykehus — Hyperbar oksygenbehandling',
    lat: 59.9045, lon: 10.7315,
    phone: '+47 22 11 80 80',
    address: 'Rikshospitalet, Sognsvannsveien 20, 0372 Oslo',
    availability: '24/7 emergency',
    notes: 'Primary Norwegian hyperbaric referral. Covers fjord and North Sea dive ops.',
    country: 'Norway',
    manual: true,
  },

  // ── Malta ─────────────────────────────────────────────────────────────────

  // Source: Malta Hyperbaric Centre; DAN Europe; Malta Tourism Authority dive info
  {
    name: 'Malta Hyperbaric Centre — Mater Dei Hospital',
    lat: 35.9009, lon: 14.4716,
    phone: '+356 2545 0000',
    address: 'Mater Dei Hospital, Msida MSD 2090, Malta',
    availability: '24/7 emergency',
    notes: 'Only chamber in Malta. Central Mediterranean. Covers Gozo as well.',
    country: 'Malta',
    manual: true,
  },

  // ── Italy ─────────────────────────────────────────────────────────────────

  // Source: Ospedale Civile di Ravenna; DAN Europe
  {
    name: "Ospedale Civile di Ravenna — Camera Iperbarica",
    lat: 44.4213, lon: 12.2035,
    phone: '+39 0544 285111',
    address: 'Via Vincenzo Randi 5, 48121 Ravenna RA',
    availability: '24/7 emergency',
    notes: 'Adriatic coast primary hyperbaric referral.',
    country: 'Italy',
    manual: true,
  },

  // Source: AOU Careggi; DAN Europe; Italian Navy
  {
    name: 'Ospedale San Martino (IRCCS) — Centro di Medicina Iperbarica',
    lat: 44.4065, lon: 8.9590,
    phone: '+39 010 555 2600',
    address: 'Largo Rosanna Benzi 10, 16132 Genova GE',
    availability: '24/7 emergency',
    notes: 'Ligurian Sea and Western Mediterranean dive casualties.',
    country: 'Italy',
    manual: true,
  },

// ── UHMS-accredited facilities (auto-generated by scripts/refreshHyperbaricChambers.mjs — do not edit this block manually) ──

  // ── United States (UHMS-accredited) ───────────────────────────────────────────────
  {
    name: "Medical Center — Center for Wound Care & Hyperbaric Medicine Springhill",
    lat: 30.6847, lon: -88.1302,
    phone: "(251) 460-5461",
    address: "Mobile, AL",
    country: "United States",
  },
  {
    name: "Medical Center — Wound Healing & Hyperbaric Oxygen Center Chandler Regional",
    lat: 33.2968, lon: -111.8741,
    phone: "(480) 728-3701",
    address: "Chandler, AZ",
    country: "United States",
  },
  {
    name: "Medical Center — UCLA Hyperbaric Medicine UCLA",
    lat: 34.0594, lon: -118.2092,
    phone: "(310) 794-9014",
    address: "Los Angeles, CA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Hyperbaric Medicine Department Redlands Community",
    lat: 34.0375, lon: -117.2065,
    phone: "(909) 335-6247",
    address: "Redlands, CA",
    country: "United States",
  },
  {
    name: "Medical Center — Hyperbaric Medicine Flight David Grant USAF",
    lat: 30.2764, lon: -97.734,
    phone: "(707) 423-3987",
    address: "Travis AFB, CA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center Walnut — Hyperbaric Medicine Department John Muir",
    lat: 37.9123, lon: -122.0404,
    phone: "(925) 947-3212",
    address: "Creek Walnut Creek, CA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Wound Care & Hyperbaric Medicine Center Loma Linda University",
    lat: 33.6066, lon: -117.162,
    phone: "(951) 290-4061",
    address: "Hospital-Murrieta Murrieta, CA",
    country: "United States",
  },
  {
    name: "University Hospital — Hyperbaric Medicine Service Loma Linda",
    lat: 34.0491, lon: -117.2638,
    phone: "(909) 558-4493",
    address: "Loma Linda, CA",
    country: "United States",
  },
  {
    name: "Hospital — The Hyperbaric Medicine Service Poudre Valley",
    lat: 40.5719, lon: -105.0564,
    phone: "(970) 495-8770",
    address: "Ft. Collins, CO",
    country: "United States",
  },
  {
    name: "Hospital — The Hyperbaric Medicine Service Memorial",
    lat: 38.8659, lon: -104.8218,
    phone: "(719) 365-5920",
    address: "Colorado Springs, CO",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hyperbaric Medicine Center",
    lat: 39.671, lon: -104.9762,
    phone: "(303) 839-6900",
    address: "Denver, CO",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Wound Healing & Hyperbaric Medicine Swedish",
    lat: 39.6543, lon: -104.9812,
    phone: "(303) 788-6660",
    address: "Englewood, CO",
    country: "United States",
  },
  {
    name: "Health Danbury Hospital — Morganti Center for Wound Care & Hyperbaric Medicine Nuvance",
    lat: 41.3873, lon: -73.5321,
    phone: "(203) 739-8167",
    address: "Danbury, CT",
    country: "United States",
  },
  {
    name: "Hospital — The Center for Hyperbaric & Wound Healing Greenwich",
    lat: 41.0343, lon: -73.6306,
    phone: "(203) 863-4505",
    address: "Greenwich, CT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Norwalk Hospital — Nuvance Health Wound Care and Hyperbaric Medicine Nuvance",
    lat: 41.1108, lon: -73.422,
    phone: "(203) 852-2434",
    address: "Norwalk, CT",
    country: "United States",
  },
  {
    name: "University Hospital — Center for Wound Healing & Hyperbaric Medicine MedStar Georgetown",
    lat: 38.9014, lon: -77.0506,
    phone: "(202)444-4268",
    address: "Washington, DC",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Hospital — Wound Healing Institute Advent",
    lat: 28.0122, lon: -82.5038,
    phone: "(813) 558-4914",
    address: "Carrollwood Tampa, FL",
    country: "United States",
  },
  {
    name: "Health Hospital — Wound Healing Institute of Brandon Advent",
    lat: 28.0122, lon: -82.5038,
    phone: "(813) 615-7100",
    address: "Carrollwood Brandon, FL",
    country: "United States",
  },
  {
    name: "Hyperbaric Medicine & Wound Care Management Center",
    lat: 37.3264, lon: -121.9386,
    phone: "(407) 303-1549",
    address: "AdventHealth Orlando Orlando, FL",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Hospital — Wound Healing Institute Advent (Tampa Tampa)",
    lat: 28.0715, lon: -82.4219,
    phone: "(813) 615-7160",
    address: "Tampa Tampa, FL",
    country: "United States",
  },
  {
    name: "Health North Pinellas — Trinity Wound Care Advent",
    lat: 28.2351, lon: -82.7206,
    phone: "(727) 203-3080",
    address: "New Port Richey, FL",
    country: "United States",
  },
  {
    name: "Health Wesley — Wound Healing Institute of Wesley Chapel Advent",
    lat: 28.1889, lon: -82.3598,
    phone: "(813) 929-5590",
    address: "Chapel Wesley Chapel, FL",
    country: "United States",
  },
  {
    name: "Medical Institute — Hyperbaric Medicine Department Naval Aerospace",
    lat: 30.4419, lon: -84.3178,
    phone: "(850) 452-3409",
    address: "Pensacola, FL",
    country: "United States",
    distinction: true,
  },
  {
    name: "Kendall Medical",
    lat: 25.731, lon: -80.3862,
    phone: "(305) 388-1118",
    address: "Center, Inc. Miami, FL",
    country: "United States",
  },
  {
    name: "Cobb Hyperbaric Medicine Regenerative & Hyperbaric Medicine, Inc",
    lat: 33.9528, lon: -84.5496,
    phone: "(770) 422-0517",
    address: "of Marrietta Marietta, GA",
    country: "United States",
    distinction: true,
  },
  {
    name: "North Georgia Center for Hyperbaric Medicine & Wound Care Regenerative & Hyperbaric Medicine, Inc",
    lat: 34.1116, lon: -84.0522,
    phone: "(770) 771-6400",
    address: "at Cumming Cumming, GA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hyperbaric Medicine of North Atlanta Regenerative & Hyperbaric Medicine, Inc at",
    lat: 33.9847, lon: -84.2992,
    phone: "(678) 843-5394",
    address: "Sandy Springs Atlanta, GA",
    country: "United States",
    distinction: true,
  },
  {
    name: "University Hospital — Emory Wound & Hyperbaric Center Emory",
    lat: 33.7703, lon: -84.3863,
    phone: "(404) 686-2800",
    address: "Midtown Atlanta, GA",
    country: "United States",
  },
  {
    name: "Hospital — WellStar North Fulton Wound Care & Hyperbarics WellStar North Fulton",
    lat: 34.0288, lon: -84.3574,
    phone: "(770) 751-2830",
    address: "Roswell, GA",
    country: "United States",
  },
  {
    name: "HyOx Medical Treatment Center",
    lat: 33.9686, lon: -84.5529,
    phone: "(678) 303-3200",
    address: "Marrietta, GA",
    country: "United States",
  },
  {
    name: "- Wound",
    lat: 47.5822, lon: -122.6277,
    phone: "(208) 489-5800",
    address: "& Hyperbaric Meridian, ID",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Wound Care & Hyperbaric Center Portneuf",
    lat: 42.8739, lon: -112.4199,
    phone: "(208) 239-2670",
    address: "Pocatello, ID",
    country: "United States",
  },
  {
    name: "Medical Center — SAMG Advanced Wound Healing & Hyperbaric Medicine Saint Alphonsus Regional",
    lat: 43.6131, lon: -116.1931,
    phone: "(208) 302-0800",
    address: "Boise, ID",
    country: "United States",
  },
  {
    name: "Medical Center — SAMG Advanced Wound Healing & Hyperbaric Medicine Saint Alphonsus Regional (Nampa)",
    lat: 43.5975, lon: -116.5172,
    phone: "(208) 302-0860",
    address: "Nampa, ID",
    country: "United States",
  },
  {
    name: "Hospital — Wound Healing & Hyperbaric Center Edward",
    lat: 41.76, lon: -88.1526,
    phone: "(630) 527-3002",
    address: "Naperville, IL",
    country: "United States",
  },
  {
    name: "Hospital — Wound Care & Hyperbaric Medicine University of Kansas",
    lat: 39.1654, lon: -94.7101,
    phone: "(913) 588-6586",
    address: "Kansas City, KS",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health — Wound Healing & Hyperbaric Center NMC",
    lat: 38.0575, lon: -97.3438,
    phone: "(316) 804-6160",
    address: "Newton, KS",
    country: "United States",
  },
  {
    name: "Healthcare — Wound Care & Hyperbaric Services Saint Elizabeth",
    lat: 37.7919, lon: -79.9968,
    phone: "(859) 655-1101",
    address: "Covington, KY",
    country: "United States",
  },
  {
    name: "Healthcare — Wound Care & Hyperbaric Services Saint Elizabeth (Ft. Thomas)",
    lat: 39.0788, lon: -84.4483,
    phone: "(859) 572-3830",
    address: "Ft. Thomas, KY",
    country: "United States",
  },
  {
    name: "Hospital Center — Wound Care & Hyperbaric Medicine Center Carroll",
    lat: 39.5741, lon: -76.9817,
    phone: "(410) 871-6334",
    address: "Westminster, MD",
    country: "United States",
  },
  {
    name: "Hospital Center — Wound Care & Hyperbaric Medicine Center Northwest",
    lat: 39.3686, lon: -76.801,
    phone: "(410) 496-7191",
    address: "Randallstown, MD",
    country: "United States",
  },
  {
    name: "UPMC Western Maryland Wound & Hyperbaric Center UPMC",
    lat: 39.6486, lon: -78.7332,
    phone: "(240) 964-8711",
    address: "Western Maryland Cumberland, MD",
    country: "United States",
  },
  {
    name: "Department of Hyperbaric Medicine University of Maryland 22 South",
    lat: 39.5112, lon: -76.5832,
    phone: "(410) 328-6152",
    address: "Greene St Baltimore, MD",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Wound Healing Center Anna Jaques",
    lat: 42.8144, lon: -70.891,
    phone: "(978) 463-1303",
    address: "Newburyport, MA",
    country: "United States",
  },
  {
    name: "Hospital — The Wound & Hyperbaric Medicine Center Beverly",
    lat: 42.5465, lon: -70.856,
    phone: "(978) 921-1210",
    address: "Beverly, MA",
    country: "United States",
  },
  {
    name: "Wound Healing & Hyperbaric Center",
    lat: 32.776, lon: -96.6003,
    phone: "(781) 396-8224",
    address: "Medford, MA",
    country: "United States",
  },
  {
    name: "Health — The Wound Care Center UMass Memorial",
    lat: 42.1439, lon: -71.97,
    phone: "(508) 248-8129",
    address: "Harrington, MA Charlton, MA",
    country: "United States",
  },
  {
    name: "Health — Hyperbaric & Dive Medicine Corewell",
    lat: 42.9693, lon: -85.6646,
    phone: "(616) 391-1269",
    address: "Grand Rapids, MI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Lakeland — Lakeland Center for Wound Care & Hyperbaric Medicine Corewell",
    lat: 41.8282, lon: -86.2602,
    phone: "(269) 683-8070",
    address: "Hospitals Niles Niles, MI",
    country: "United States",
  },
  {
    name: "Medical Center — x8528 Minnesota *Hyperbaric Medicine Hennepin County",
    lat: 44.9712, lon: -93.2604,
    phone: "(612) 873-7420",
    address: "Minneapolis, MN",
    country: "United States",
  },
  {
    name: "Clinic — Hyperbaric & Altitude Medicine Program Mayo",
    lat: 44.0193, lon: -92.481,
    phone: "(507) 538-7210",
    address: "Rochester, MN",
    country: "United States",
    distinction: true,
  },
  {
    name: "Clinic Health System-Albert — Wound Care & Hyperbaric Medicine Mayo",
    lat: 44.1636, lon: -93.9844,
    phone: "(507) 377-4165",
    address: "Lea Albert Lea, MN",
    country: "United States",
  },
  {
    name: "Hospital — Wound Healing & Hyperbaric Center North Kansas City",
    lat: 39.1499, lon: -94.5514,
    phone: "(816) 691-5055",
    address: "North Kansas City, MO",
    country: "United States",
  },
  {
    name: "Healthcare — Cox Hyperbaric Medicine & Wound Care Center Cox",
    lat: 37.1474, lon: -93.2773,
    phone: "(417) 269-9950",
    address: "Springfield, MO",
    country: "United States",
  },
  {
    name: "Hospital — Wound Care & Hyperbaric Medicine Center Freeman",
    lat: 37.0535, lon: -94.5384,
    phone: "(413) 347-4800",
    address: "Joplin, MO",
    country: "United States",
  },
  {
    name: "Clinic Bozeman Health Deaconess Hospital — Bozeman Health Wound & Hyperbaric",
    lat: 45.6697, lon: -111.0209,
    phone: "(406) 414-5512",
    address: "Bozeman, MT",
    country: "United States",
  },
  {
    name: "Medical Center — Hyperbaric Medicine Center Nebraska",
    lat: 41.2551, lon: -95.977,
    phone: "(402) 552-2490",
    address: "Omaha, NE",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — CH Wound & Hyperbaric Center Concord",
    lat: 43.2002, lon: -71.5634,
    phone: "(603) 230-1970",
    address: "Concord, NH",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Hyperbaric Medicine Dartmouth-Hitchcock",
    lat: 43.6757, lon: -72.2701,
    phone: "(603) 650-6489",
    address: "Lebanon, NH",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Carole & Joseph Katz, MD Wound Healing Center Overlook",
    lat: 40.7126, lon: -74.3535,
    phone: "(908) 522-5900",
    address: "Summit, NJ",
    country: "United States",
  },
  {
    name: "Hyperbaric Services",
    lat: 40.479, lon: -74.4756,
    phone: "(732) 745-8600",
    address: "Saint New Brunswick, NJ",
    country: "United States",
  },
  {
    name: "Medical Center — ext 6858 Comprehensive Wound Healing & Hyperbaric Center Chilton",
    lat: 40.9582, lon: -74.3099,
    phone: "(973) 831-5303",
    address: "Pompton Plains, NJ",
    country: "United States",
  },
  {
    name: "Medical Center — AtlantiCare Wound Healing Center AtlantiCare Regional",
    lat: 39.3469, lon: -74.6053,
    phone: "(609) 407-2205",
    address: "Egg Harbor Township, NJ",
    country: "United States",
  },
  {
    name: "University Hospital — Hyperbaric Medicine & Wound Care Center Upstate",
    lat: 43.0426, lon: -76.1402,
    phone: "(315) 464-4910",
    address: "Syracuse, NY",
    country: "United States",
    distinction: true,
  },
  {
    name: "Center for Wound Care & Hyperbaric Medicine",
    lat: 37.3264, lon: -121.9386,
    phone: "(315) 329-7770",
    address: "Fayetteville, NY",
    country: "United States",
  },
  {
    name: "Hospital — Center for Hyperbaric Medicine and Wound Healing St. Joseph",
    lat: 40.7263, lon: -73.4789,
    phone: "(516) 520-2788",
    address: "Bethpage, NY",
    country: "United States",
  },
  {
    name: "Medical Center — Westchester Hyperbaric Center Westchester",
    lat: 41.0874, lon: -73.8067,
    phone: "(914) 493-1500",
    address: "Valhalla, NY",
    country: "United States",
  },
  {
    name: "Health Good Samaritan Regional Medical Center — Wound & Hyperbaric Institute at Good Samaritan WMC",
    lat: 44.6026, lon: -123.2527,
    phone: "(845) 368-5590",
    address: "Suffern, NY",
    country: "United States",
  },
  {
    name: "NYU Langone-Long Island Hyperbaric Medicine Program NYU Langone",
    lat: 40.7408, lon: -73.6426,
    phone: "(516) 663-8498",
    address: "Hospital-Long Island Mineola, NY",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Plainview Hospital — Hyperbaric Medicine & Wound Care Northwell",
    lat: 42.3586, lon: -97.7858,
    phone: "(516) 796-1313",
    address: "Plainview, NY",
    country: "United States",
  },
  {
    name: "Health Vassar Brothers Medical Center — Nuvance Health Wound Care and Hyperbaric Medicine Nuvance",
    lat: 41.6936, lon: -73.9348,
    phone: "(845) 431-2400",
    address: "Poughkeepsie, NY",
    country: "United States",
  },
  {
    name: "Health Medical — Wound Healing Center Garnet",
    lat: 41.7094, lon: -74.7373,
    phone: "(845) 794-3300",
    address: "Center-Catskills Harris, NY",
    country: "United States",
  },
  {
    name: "Health Medical — Wound Healing Center Garnet (Center-Orange Middletown)",
    lat: 41.4423, lon: -74.3683,
    phone: "(845) 333-7700",
    address: "Center-Orange Middletown, NY",
    country: "United States",
  },
  {
    name: "Hospital/Northwell Health — Department of Hyperbaric Medicine Phelps",
    lat: 41.1095, lon: -73.864,
    phone: "(914) 366-3000",
    address: "Sleepy Hollow, NY",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Ext 3690 Wound Care & Hyperbaric Medicine United Memorial",
    lat: 43.0058, lon: -78.1769,
    phone: "(585) 344-5372",
    address: "Batavia, NY",
    country: "United States",
  },
  {
    name: "Health Putnam Hospital — Nuvance Health Wound Care and Hyperbaric Medicine Nuvance",
    lat: 41.3841, lon: -73.6632,
    phone: "(845) 278-5683",
    address: "Carmel, NY",
    country: "United States",
  },
  {
    name: "Center for",
    lat: 40.4951, lon: -74.4484,
    phone: "(845) 458-4512",
    address: "Wound Healing Cornwall, NY",
    country: "United States",
  },
  {
    name: "Hospital — Wound Healing Center Strong Memorial",
    lat: 43.1229, lon: -77.6254,
    phone: "(585) 262-9100",
    address: "Rochester, NY",
    country: "United States",
  },
  {
    name: "Health Northern Dutchess Hospital — Nuvance Health Wound Care and Hyperbaric Medicine Nuvance",
    lat: 41.9355, lon: -73.9129,
    phone: "(845) 871-3888",
    address: "Rhinebeck, NY",
    country: "United States",
  },
  {
    name: "Hospital of Westchester Medical Center — Wound Healing & Hyperbaric Medicine MidHudson Regional",
    lat: 41.0874, lon: -73.8067,
    phone: "(845) 431-8144",
    address: "Poughkeepsie, NY",
    country: "United States",
  },
  {
    name: "Medical Center — Rev. Thomas T. Patterson Wound Healing Center Claxton-Hepburn",
    lat: 44.6915, lon: -75.4993,
    phone: "(315) 394-0426",
    address: "Ogdensburg, NY",
    country: "United States",
  },
  {
    name: "Hospital Albany — The Center for Wound Care & Hyperbaric Medicine Samaritan",
    lat: 42.6737, lon: -73.7486,
    phone: "(518) 471-3705",
    address: "Memorial Campus Albany, NY",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Wound Healing Arnot Ogden",
    lat: 42.1002, lon: -76.8273,
    phone: "(607) 737-7773",
    address: "Elmira, NY",
    country: "United States",
  },
  {
    name: "Center for Wound Healing & Hyperbaric Medicine",
    lat: 37.3264, lon: -121.9386,
    phone: "(716) 298-3012",
    address: "Mount Lewiston, NY",
    country: "United States",
  },
  {
    name: "Hospital of — Catholic Health Advanced Wound Healing Centers Mercy",
    lat: 42.7666, lon: -78.7435,
    phone: "(716) 828-2330",
    address: "Buffalo Orchard Park, NY",
    country: "United States",
  },
  {
    name: "Catholic Health Advanced Wound Healing Centers St.",
    lat: 34.2021, lon: -84.7932,
    phone: "(716) 891-2570",
    address: "Joseph Campus Cheektowaga, NY",
    country: "United States",
  },
  {
    name: "University Hospital — Comprehensive Wound Care Center North Shore",
    lat: 40.5854, lon: -74.0848,
    phone: "(516) 233-3664",
    address: "New Hyde Park, NY",
    country: "United States",
  },
  {
    name: "Medical Center — Helen L. & Martin S. Kimmel Hyperbaric & Advanced Wound Healing Center NYU Langone",
    lat: 40.7423, lon: -73.9736,
    phone: "(212) 598-6500",
    address: "New York, NY",
    country: "United States",
  },
  {
    name: "Center for Advanced Wound Care & Hyperbaric Medicine",
    lat: 37.3264, lon: -121.9386,
    phone: "(914) 378-7900",
    address: "Yonkers, NY",
    country: "United States",
  },
  {
    name: "Health — Wound Care & Hyperbaric Medicine Center Oneida",
    lat: 43.088, lon: -75.2486,
    phone: "(315) 361-2268",
    address: "Oneida, NY",
    country: "United States",
  },
  {
    name: "The Center for Wound Care & Hyperbaric Medicine NYU",
    lat: 37.3264, lon: -121.9386,
    phone: "(631) 687-4190",
    address: "Langone Hospital-Suffolk Patchogue, NY",
    country: "United States",
  },
  {
    name: "Hospital — The Carl Webber Center for Wound Healing & Hyperbaric Medicine White Plains",
    lat: 41.0258, lon: -73.7693,
    phone: "(914) 681-2430",
    address: "White Plains, NY",
    country: "United States",
  },
  {
    name: "Health System Hyperbarics Mohawk Valley Health System Advanced Wound — Mohawk Valley",
    lat: 43.0712, lon: -75.345,
    phone: "(315)738-4901",
    address: "Care New Hartford, NY",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Hyperbaric Medicine & Environmental Physiology Duke University",
    lat: 36.1376, lon: -78.8138,
    phone: "(919) 684-6726",
    address: "Durham, NC",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health — Hyperbaric & Dive Medicine Department Essentia",
    lat: 46.8045, lon: -96.8481,
    phone: "(701) 364-7555",
    address: "Fargo Fargo, ND",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Riverside Methodist Hospital — Hyperbaric Medicine Program Ohio",
    lat: 40.0311, lon: -83.0347,
    phone: "(614) 566-3251",
    address: "Columbus, OH",
    country: "United States",
  },
  {
    name: "Hospital — Samaritan Wound, Vein, & Hyperbaric Medicine Samaritan Albany General",
    lat: 44.6321, lon: -123.1171,
    phone: "(541) 812-3360",
    address: "Albany, OR",
    country: "United States",
  },
  {
    name: "Hospital — Wound Healing & Hyperbaric Medicine Center Reading",
    lat: 40.338, lon: -75.9577,
    phone: "(484) 628-3939",
    address: "Wyomissing, PA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Carlisle Wound & Hyperbaric Center",
    lat: 32.776, lon: -96.6003,
    phone: "(717) 243-1900",
    address: "UPMC Carlisle Carlisle, PA",
    country: "United States",
    distinction: true,
  },
  {
    name: "UPMC Pinnacle Wound & Hyperbaric Center-East UPMC",
    lat: 40.2879, lon: -76.8989,
    phone: "(717) 671-2050",
    address: "Pinnacle Harrisburg Harrisburg, PA",
    country: "United States",
    distinction: true,
  },
  {
    name: "UPMC Pinnacle Wound & Hyperbaric Center-West UPMC Pinnacle",
    lat: 40.2361, lon: -77.0061,
    phone: "(717) 791-2440",
    address: "West Shore Mechanicsburg, PA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — WellSpan Center for Wound Healing & Hyperbaric Services WellSpan Ephrata Community",
    lat: 40.1663, lon: -76.1619,
    phone: "(717) 738-6527",
    address: "Ephrata, PA",
    country: "United States",
  },
  {
    name: "Hospital — WellSpan Wound Healing Center WellSpan Good Samaritan",
    lat: 40.3364, lon: -76.4167,
    phone: "(717) 675-2545",
    address: "Lebanon, PA",
    country: "United States",
  },
  {
    name: "Hospital — Guthrie Center for Wound Care & Hyperbaric Medicine Robert Packer",
    lat: 41.9806, lon: -76.5208,
    phone: "(570) 887-6639",
    address: "Sayre, PA",
    country: "United States",
  },
  {
    name: "Hospital — Wound Recovery & Hyperbaric Medicine Center Kent",
    lat: 41.706, lon: -71.4772,
    phone: "(401) 736-4646",
    address: "Warwick, RI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health Medical Center — Wound Care & Hyperbaric Medicine Center Regional One",
    lat: 35.1407, lon: -90.0297,
    phone: "(901) 545-8999",
    address: "Memphis, TN",
    country: "United States",
    distinction: true,
  },
  {
    name: "Clinic Brooke Army Medical Center — Undersea & Hyperbaric Medicine",
    lat: 29.4612, lon: -98.4156,
    phone: "(210) 539-8000",
    address: "San Antonio, TX",
    country: "United States",
    distinction: true,
  },
  {
    name: "Health — Wound Healing Center UT",
    lat: 32.3326, lon: -95.2902,
    phone: "(903) 526-4325",
    address: "East Texas Tyler, TX",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Wound Care & Hyperbaric Medicine Center Methodist Dallas",
    lat: 32.8095, lon: -96.8375,
    phone: "(214) 947-5000",
    address: "Dallas, TX",
    country: "United States",
  },
  {
    name: "Health Presbyterian Hospital — Institute for Exercise & Environmental Medicine Texas",
    lat: 32.8798, lon: -96.7624,
    phone: "(214) 345-4651",
    address: "Dallas Dallas, TX",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Wound Care & Hyperbaric Center Methodist Charlton",
    lat: 32.8095, lon: -96.8375,
    phone: "(214) 947-0752",
    address: "Dallas, TX",
    country: "United States",
  },
  {
    name: "Medical Center — Louise Gartner Center for Hyperbaric Medicine Baylor University",
    lat: 32.8095, lon: -96.8375,
    phone: "(214) 820-4400",
    address: "Dallas, TX",
    country: "United States",
  },
  {
    name: "Medical Center at Irving Irving, Texas (972) 579-5222 Wound Care & Hyperbaric Medicine Clinic Baylor Scott & White Medical Center — Comprehensive Wound Center Las Colinas Baylor Scott & White",
    lat: 31.0984, lon: -97.343,
    phone: "(254) 724-6622",
    address: "Temple, TX",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center South San Angelo, Texas (325) 947-6960 *Memorial Hermann Center for Hyperbaric Medicine Memorial Hermann Hospital — Wound Care & Hyperbaric Services Shannon",
    lat: 29.7589, lon: -95.3677,
    phone: "(713) 704-5900",
    address: "Houston, TX",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Hyperbaric Medicine Las Palmas",
    lat: 31.8214, lon: -106.4622,
    phone: "(915) 521-1200",
    address: "El Paso, TX",
    country: "United States",
  },
  {
    name: "Hospital — Hyperbaric Medicine Department LDS",
    lat: 40.7715, lon: -111.8365,
    phone: "(801) 408-3623",
    address: "Salt Lake City, UT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Utah Valley Wound Care & Hyperbaric Medicine Center Utah Valley Regional",
    lat: 40.2479, lon: -111.6657,
    phone: "(801) 357-8156",
    address: "Provo, UT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Department of Hyperbaric Medicine St. George Regional",
    lat: 37.0988, lon: -113.5759,
    phone: "(435) 688-4293",
    address: "St. George, UT",
    country: "United States",
  },
  {
    name: "Medical Center — Hyperbaric Medicine Intermountain",
    lat: 40.6596, lon: -111.8912,
    phone: "(801) 408-3623",
    address: "Murray, UT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Hyperbaric & Wound Center Holy Cross",
    lat: 41.0911, lon: -111.9953,
    phone: "(801) 807-7900",
    address: "Davis Layton, UT",
    country: "United States",
  },
  {
    name: "Hospital — McKay-Dee Wound & Hyperbaric Center McKay-Dee",
    lat: 41.1833, lon: -111.9539,
    phone: "(801) 387-4886",
    address: "Ogden, UT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital-Jordan — Hyperbaric & Wound Center Holy Cross",
    lat: 40.5896, lon: -111.9746,
    phone: "(801) 601-2322",
    address: "Valley West Jordan, UT",
    country: "United States",
  },
  {
    name: "Hospital — Logan Regional Wound & Hyperbaric Center Intermountain Logan Regional",
    lat: 41.756, lon: -111.8216,
    phone: "(435) 716-2834",
    address: "Logan, UT",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Wound Care & Hyperbaric Medicine Lakeview",
    lat: 40.8808, lon: -111.8929,
    phone: "(801) 397-0890",
    address: "Bountiful, UT",
    country: "United States",
  },
  {
    name: "Hospital — Hyperbaric Medicine Unit Inova Mount Vernon",
    lat: 38.8224, lon: -77.1047,
    phone: "(703) 664-7218",
    address: "Alexandria, VA",
    country: "United States",
  },
  {
    name: "Hospital — Department of Hyperbaric Medicine Retreat",
    lat: 37.584, lon: -77.5129,
    phone: "(804) 254-5313",
    address: "Richmond, VA",
    country: "United States",
  },
  {
    name: "Hospital Center — The Wound Healing & Hyperbaric Center Virginia",
    lat: 38.8425, lon: -77.0846,
    phone: "(703) 558-6600",
    address: "Arlington, VA",
    country: "United States",
  },
  {
    name: "Medical Center — Center for Hyperbaric Medicine Virginia Mason",
    lat: 47.6102, lon: -122.3279,
    phone: "(206) 583-6543",
    address: "Seattle, WA",
    country: "United States",
    distinction: true,
  },
  {
    name: "Hospital — Center for Wound Healing & Hyperbaric Swedish Edmonds",
    lat: 47.8076, lon: -122.3462,
    phone: "(425) 673-3380",
    address: "Edmonds, WA",
    country: "United States",
  },
  {
    name: "Center for Comprehensive Wound Care & Hyperbaric Medicine",
    lat: 37.3264, lon: -121.9386,
    phone: "(414) 649-6609",
    address: "Aurora Milwaukee, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora West Allis",
    lat: 43.0023, lon: -88.0243,
    phone: "(414) 649-6577",
    address: "West Allis, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora",
    lat: 41.7537, lon: -72.6816,
    phone: "(414) 328-8404",
    address: "Washington County Hartford, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora",
    lat: 44.0135, lon: -88.5449,
    phone: "(920) 456-7407",
    address: "Center-Oshkosh Oshkosh, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora (in Summit Summit)",
    lat: 43.0569, lon: -87.8853,
    phone: "(262) 434-1000",
    address: "in Summit Summit, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora (in Grafton Grafton)",
    lat: 43.3259, lon: -87.9279,
    phone: "(262) 329-1080",
    address: "in Grafton Grafton, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center Manitowoc — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora",
    lat: 44.1266, lon: -87.6176,
    phone: "(920) 794-5450",
    address: "County Two Rivers, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora BayCare",
    lat: 44.5339, lon: -88.0664,
    phone: "(920) 288-4358",
    address: "Green Bay, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical Center — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora (Burlington Burlington)",
    lat: 40.0462, lon: -74.88,
    phone: "(262) 767-4684",
    address: "Burlington Burlington, WI",
    country: "United States",
    distinction: true,
  },
  {
    name: "Medical — Center for Comprehensive Wound Care & Hyperbaric Medicine Aurora (Center-Kenosha Kenosha)",
    lat: 42.5777, lon: -87.82,
    phone: "(262) 948-5702",
    address: "Center-Kenosha Kenosha, WI",
    country: "United States",
    distinction: true,
  },

  // ── Ireland (UHMS-accredited) ─────────────────────────────────────────────────────
  {
    name: "Oxycare Medical Hyperbaric Treatment Center Santry",
    lat: 53.3494, lon: -6.2606,
    phone: "(08) 7250-6552",
    address: "Dublin, Ireland",
    country: "Ireland",
  },

  // ── Singapore (UHMS-accredited) ───────────────────────────────────────────────────
  {
    name: "Medical Squadron (UM SQN) Republic of Singapore Navy — Underwater",
    lat: 1.3571, lon: 103.8195,
    phone: "(65) 6796-4197",
    address: "Singapore, Singapore",
    country: "Singapore",
    distinction: true,
  },

  // ── United Arab Emirates (UHMS-accredited) ────────────────────────────────────────
  {
    name: "Centre — Hyperbaric Department The Brain & Performance",
    lat: 25.0042, lon: 55.1541,
    phone: "(971)04437-1000",
    address: "Dubai, United Arab Emirates",
    country: "United Arab Emirates",
  },

]

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Haversine distance in metres (inlined to avoid circular-dependency). */
function haversineM(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6_371_000
  const φ1 = (lat1 * Math.PI) / 180
  const φ2 = (lat2 * Math.PI) / 180
  const dφ = ((lat2 - lat1) * Math.PI) / 180
  const dλ = ((lon2 - lon1) * Math.PI) / 180
  const a = Math.sin(dφ / 2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin(dλ / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Return all chambers within `radiusM` metres of `target`.
 *
 * Used in the fetch pipeline (`App.tsx → mergeFacilities`) to inject in-radius
 * chambers into the facility list whenever coordinates are set (regardless of
 * dive mode — they carry the 'hyperbaric' capability and only surface in the
 * Chamber PACE when dive mode is active).
 */
export function selectChambersInRadius(
  target: LatLon,
  radiusM: number,
): readonly HyperbaricChamber[] {
  return HYPERBARIC_CHAMBERS.filter(
    c => haversineM(target.lat, target.lon, c.lat, c.lon) <= radiusM,
  )
}

/** Exported for unit tests only — do not import in production code. */
export const _testOnly = { HYPERBARIC_CHAMBERS }
